2018-05-16 23:00:24 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:24 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:26 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:26 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:31 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:00:31 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:00:33 [signal_handler DEBUG] App ready signal recv
2018-05-16 23:00:33 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-16 23:00:34 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-16 23:00:34 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-16 23:00:34 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-16 23:23:21 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:21 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:23 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:23 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:27 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:27 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:27 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:27 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:28 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:28 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:28 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:28 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:29 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:29 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:29 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:23:29 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:23:31 [signal_handler DEBUG] App ready signal recv
2018-05-16 23:23:31 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_orphan_session]
2018-05-16 23:23:32 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-16 23:23:32 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-16 23:23:32 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-16 23:27:54 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:27:54 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:27:58 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:27:58 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:03 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:03 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:03 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:03 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:03 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:03 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:03 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:03 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:03 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:03 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:04 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:28:04 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:28:07 [signal_handler DEBUG] App ready signal recv
2018-05-16 23:28:07 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_orphan_session]
2018-05-16 23:28:08 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-16 23:28:08 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-16 23:28:08 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-16 23:29:04 [exception ERROR] Internal Server Error: /users/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 18, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 373, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")
2018-05-16 23:29:04 [base WARNING] Not Found: /favicon.ico
2018-05-16 23:29:26 [exception ERROR] Internal Server Error: /users/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 18, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 373, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")
2018-05-16 23:30:35 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:30:35 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:30:38 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:30:38 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:43 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:43 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:46 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:46 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:50 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:50 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:50 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:50 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:51 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:51 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:51 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:51 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:51 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:51 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:51 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:31:51 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:31:53 [signal_handler DEBUG] App ready signal recv
2018-05-16 23:31:53 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-16 23:31:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-16 23:31:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-16 23:31:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-16 23:32:44 [exception ERROR] Internal Server Error: /users/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 18, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 373, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")
2018-05-16 23:36:45 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:36:45 [signals_handler DEBUG]   - fresh all settings
2018-05-16 23:36:47 [signals_handler DEBUG] Receive django ready signal
2018-05-16 23:36:47 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:00:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:00:37 [signal_handler DEBUG] App ready signal recv
2018-05-17 10:00:37 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-17 10:00:38 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-17 10:00:38 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-17 10:00:38 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-17 10:02:01 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:02:01 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:02:04 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:02:04 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:02:52 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:02:52 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:02:54 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:02:54 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:06:47 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:06:47 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:06:49 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:06:49 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:21:33 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:21:33 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:21:35 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:21:35 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:25:59 [exception ERROR] Internal Server Error: /users/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 18, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 373, in get
    num = len(clone)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")
2018-05-17 10:26:00 [base WARNING] Not Found: /favicon.ico
2018-05-17 10:26:00 [base WARNING] Not Found: /favicon.ico
2018-05-17 10:34:25 [signal_handler DEBUG] App shutdown signal recv
2018-05-17 10:34:25 [signal_handler DEBUG] Clean need cleaned period tasks: []
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:57 [signals_handler DEBUG] Receive django ready signal
2018-05-17 10:41:57 [signals_handler DEBUG]   - fresh all settings
2018-05-17 10:41:59 [signal_handler DEBUG] App ready signal recv
2018-05-17 10:41:59 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-17 10:42:00 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-17 10:42:00 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-17 10:42:00 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 09:07:31 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:31 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:31 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:31 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:31 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:31 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:31 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:31 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 09:07:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 09:07:35 [signal_handler DEBUG] App ready signal recv
2018-05-18 09:07:35 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 09:07:35 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 09:07:35 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 09:07:35 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 11:16:55 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:16:55 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:16:55 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:16:55 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:16:59 [signal_handler DEBUG] App ready signal recv
2018-05-18 11:16:59 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 11:16:59 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 11:16:59 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 11:16:59 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 11:24:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 11:24:56 [signal_handler DEBUG] App ready signal recv
2018-05-18 11:24:56 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 11:24:57 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 11:24:57 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 11:24:57 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 11:25:31 [signal_handler WARNING] Not get the task: a90c9279-0344-4e5c-9abf-474d9bdb16ff
2018-05-18 12:24:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 12:24:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 12:24:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 13:24:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 13:24:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 13:24:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 14:24:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 14:24:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 14:24:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:22 [signals_handler DEBUG] Receive django ready signal
2018-05-18 14:35:22 [signals_handler DEBUG]   - fresh all settings
2018-05-18 14:35:25 [signal_handler DEBUG] App ready signal recv
2018-05-18 14:35:25 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 14:35:26 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 14:35:26 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 14:35:26 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 14:38:48 [signal_handler DEBUG] App shutdown signal recv
2018-05-18 14:38:48 [signal_handler DEBUG] Clean need cleaned period tasks: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 15:06:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:32 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:32 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:33 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:06:33 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:06:36 [signal_handler DEBUG] App shutdown signal recv
2018-05-18 15:06:36 [signal_handler DEBUG] Clean need cleaned period tasks: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 15:17:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:53 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:17:53 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:17:57 [signal_handler DEBUG] App ready signal recv
2018-05-18 15:17:57 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 15:17:57 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 15:17:57 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 15:17:57 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 15:21:45 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:21:45 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:21:45 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:21:45 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:21:46 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:21:46 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:21:46 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:21:46 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:22:20 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:22:20 [signals_handler DEBUG]   - fresh all settings
2018-05-18 15:22:20 [signals_handler DEBUG] Receive django ready signal
2018-05-18 15:22:20 [signals_handler DEBUG]   - fresh all settings
2018-05-18 16:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 16:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 16:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 16:58:49 [signal_handler DEBUG] App shutdown signal recv
2018-05-18 16:58:50 [signal_handler DEBUG] Clean need cleaned period tasks: []
2018-05-18 16:58:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 16:58:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 16:58:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 16:58:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 16:58:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 16:58:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 16:58:52 [signals_handler DEBUG] Receive django ready signal
2018-05-18 16:58:52 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:56 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:56 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:57 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:57 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:57 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:57 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:57 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:57 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:58 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:58 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:11:58 [signals_handler DEBUG] Receive django ready signal
2018-05-18 17:11:58 [signals_handler DEBUG]   - fresh all settings
2018-05-18 17:12:01 [signal_handler DEBUG] App ready signal recv
2018-05-18 17:12:01 [signal_handler DEBUG] Start need start task: [assets.tasks.update_assets_hardware_info_period, assets.tasks.test_admin_user_connectability_period, assets.tasks.test_system_user_connectability_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session]
2018-05-18 17:12:01 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 17:12:01 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 17:12:01 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 17:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 17:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 17:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 18:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 18:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 18:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 19:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 19:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 19:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 20:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 20:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 20:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 21:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 21:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 21:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 22:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 22:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 22:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-18 23:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-18 23:17:54 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-18 23:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 00:17:54 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 00:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 00:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 01:17:54 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 01:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 01:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 02:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 02:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 02:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 03:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 03:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 03:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 04:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 04:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 04:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 05:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 05:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 05:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 06:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 06:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 06:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 07:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 07:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 07:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 08:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 08:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 08:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 09:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 09:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 09:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 10:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 10:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 10:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 11:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 11:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 11:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 12:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 12:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 12:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 13:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 13:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 13:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 14:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 14:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 14:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 15:17:55 [tasks DEBUG] Period task disabled, test system user connectability pass
2018-05-19 15:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 15:17:56 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 16:17:55 [tasks DEBUG] Period task disabled, update assets hardware info pass
2018-05-19 16:17:55 [tasks DEBUG] Period task disabled, test admin user connectability pass
2018-05-19 16:17:56 [tasks DEBUG] Period task disabled, test system user connectability pass
